### PR TITLE
UPDATE CliSyntax.java

### PR DESCRIPTION
**Pull request by Statspadders**
Changing AB3 syntax to ModCheck syntax
Add feature now works for ModCheck

Things to improve: (not yet implemented)
Currently using AB3 address field for ModCheck description field.
Need to remove AB3 address class/field, might affect a lot of things (Storage,etc)

### CODE REVIEW

**Comment by Acerizm** [comment]
@Statspadders why must the format change from the original one?

**Comment by Statspadders** [comment]
> @Statspadders why must the format change from the original one?

AB3 format uses t/ for tags , p/ for phone number and a/ for address
I updated to m/ for modules, c/ for contact number and d/ for description , not format buy syntax* oops

**Comment by Acerizm** [comment]
I think `t/tags` needs to stay as it's can represent `TA`, `Professors`, `Classmate` etc.  ( it is also part of my feature ) and if you change `p/ phone numbers` to `/c contact numbers`, you need to update all of `/p phone numbers` references in User Guide and Developer Guide. 

The address can be replaced with description no problem.

**Comment by Statspadders** [comment]
Agree. t/tags will be used for TA,Profs,Classmate. Originally, i thought the description field was to represent TA prof or classmate, so do we still need a description field ?

Will do m/ module tags for module codes in later iterations. Tags and Module tags will have different colour.

**Comment by Acerizm** [comment]
I think description field is needed which you suggested could be `d/`. The address ( not email address ) `a/` can be changed to `d/`. This allows @Gibson0918 view command to reflect somewhat below by his suggested ui below.

I think linking up with @Gibson0918 for your feature is good because his command requires your `d/` field and `m/` field. Can also assume the `t/` tag is there as well. 

image

**Comment by Statspadders** [comment]
Have updated the CliSyntax. 

Syntax:

n/ for name
e/ for email
d/ for description (currently is using the address class)
p/ phone number
t/ tag number

m/ module number(not implemented)

**Review by Gibson0918 — APPROVED** [review]
LGTM.

**Pull request merged**
