### PR TITLE
Modified code to hide the visibility of contact details

### PR DESCRIPTION
**Pull request by Gibson0918**
Modified code to hide the visibility of contact details of all command except view command.

### CODE REVIEW

**Comment by Gibson0918** [comment]
There's a bug here where the contact details are shown. Refer to the video in the telegram group for more info. 
**Don't merge this yet!!!!!**

**Comment by Gibson0918** [comment]
@Acerizm Help me check if it's working fine. Thanks!

**Comment by Acerizm** [comment]
Currently list -> view -> filter -> list is broken. Have yet to test the rest of the commands

**Comment by Statspadders** [comment]
For mine dataset, view -> list, is broken.  Few days back, I tried to debug, I also cant seem to find the bug, abit weird how javafx updates their PersonListPanel.

@Gibson0918 If it is too time consuming, this feature can make do without it.

**Comment by Gibson0918** [comment]
@Statspadders Did u try with the latest commit? It is working on my end. Maybe you can take a video and post it on the telegram group so I can better understand the issue?

Here's a short video of what I tested:
https://user-images.githubusercontent.com/40551779/228500354-096d2ad0-80ef-40f0-b75f-e633390452a2.mp4

The only buggy part is the edit interaction. I unsure if users are allowed to edit since all contacts details are hidden.

**Comment by Statspadders** [comment]
Oops sorry was looking at the wrong commit. 

I am facing this bug. Can you try on your end ? 

view (all indexes) 
add a new user
Some of the contacts are hidden and some are not.

**Comment by Gibson0918** [comment]
@Statspadders Updated the code and it was working when I tested the bug that you mentioned. If there are any other bugs, then lmk and I'll try to fix it? Otherwise, if everything looks good then help me to approve and merge, Thanks! 

> view (all indexes)
>add a new user
>Some of the contacts are hidden and some are not.

**Pull request merged**
